# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editor.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(834, 675)
        MainWindow.setDocumentMode(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sceneGraphicsView = RuminaGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneGraphicsView.sizePolicy().hasHeightForWidth())
        self.sceneGraphicsView.setSizePolicy(sizePolicy)
        self.sceneGraphicsView.setObjectName("sceneGraphicsView")
        self.verticalLayout_2.addWidget(self.sceneGraphicsView)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabWidgetPage1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox = QtWidgets.QGroupBox(self.tabWidgetPage1)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_15.setContentsMargins(6, 2, 6, 5)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.name = QtWidgets.QLineEdit(self.groupBox)
        self.name.setObjectName("name")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(4)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setSliderPosition(2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setTickInterval(1)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider)
        self.verticalLayout_15.addLayout(self.formLayout_2)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.highlighted = QtWidgets.QCheckBox(self.groupBox)
        self.highlighted.setObjectName("highlighted")
        self.horizontalLayout_23.addWidget(self.highlighted)
        self.hidden = QtWidgets.QCheckBox(self.groupBox)
        self.hidden.setObjectName("hidden")
        self.horizontalLayout_23.addWidget(self.hidden)
        self.verticalLayout_15.addLayout(self.horizontalLayout_23)
        self.verticalLayout_14.addWidget(self.groupBox)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalGroupBox_2.sizePolicy().hasHeightForWidth())
        self.horizontalGroupBox_2.setSizePolicy(sizePolicy)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.horizontalGroupBox_2)
        self.verticalLayout_4.setContentsMargins(6, 2, 6, 5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.x = QtWidgets.QDoubleSpinBox(self.horizontalGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x.sizePolicy().hasHeightForWidth())
        self.x.setSizePolicy(sizePolicy)
        self.x.setObjectName("x")
        self.horizontalLayout_6.addWidget(self.x)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_7 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_9.addWidget(self.label_7)
        self.y = QtWidgets.QDoubleSpinBox(self.horizontalGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.y.sizePolicy().hasHeightForWidth())
        self.y.setSizePolicy(sizePolicy)
        self.y.setObjectName("y")
        self.horizontalLayout_9.addWidget(self.y)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.z = QtWidgets.QDoubleSpinBox(self.horizontalGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.z.sizePolicy().hasHeightForWidth())
        self.z.setSizePolicy(sizePolicy)
        self.z.setObjectName("z")
        self.horizontalLayout_10.addWidget(self.z)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_17 = QtWidgets.QLabel(self.horizontalGroupBox_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.scale = QtWidgets.QSlider(self.horizontalGroupBox_2)
        self.scale.setMaximum(200)
        self.scale.setProperty("value", 100)
        self.scale.setOrientation(QtCore.Qt.Horizontal)
        self.scale.setObjectName("scale")
        self.horizontalLayout_24.addWidget(self.scale)
        self.scaleVal = QtWidgets.QDoubleSpinBox(self.horizontalGroupBox_2)
        self.scaleVal.setMinimum(0.01)
        self.scaleVal.setMaximum(2.0)
        self.scaleVal.setSingleStep(0.01)
        self.scaleVal.setProperty("value", 1.0)
        self.scaleVal.setObjectName("scaleVal")
        self.horizontalLayout_24.addWidget(self.scaleVal)
        self.formLayout_7.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_24)
        self.verticalLayout_4.addLayout(self.formLayout_7)
        self.verticalLayout_14.addWidget(self.horizontalGroupBox_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setContentsMargins(6, 2, 6, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.file = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.file.sizePolicy().hasHeightForWidth())
        self.file.setSizePolicy(sizePolicy)
        self.file.setAlignment(QtCore.Qt.AlignCenter)
        self.file.setObjectName("file")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.file)
        self.verticalLayout.addLayout(self.formLayout_6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.sx = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sx.sizePolicy().hasHeightForWidth())
        self.sx.setSizePolicy(sizePolicy)
        self.sx.setObjectName("sx")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sx)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sy = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sy.sizePolicy().hasHeightForWidth())
        self.sy.setSizePolicy(sizePolicy)
        self.sy.setObjectName("sy")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sy)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.sh = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sh.sizePolicy().hasHeightForWidth())
        self.sh.setSizePolicy(sizePolicy)
        self.sh.setObjectName("sh")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sh)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sw = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sw.sizePolicy().hasHeightForWidth())
        self.sw.setSizePolicy(sizePolicy)
        self.sw.setObjectName("sw")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sw)
        self.horizontalLayout_3.addLayout(self.formLayout_4)
        self.crop = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crop.sizePolicy().hasHeightForWidth())
        self.crop.setSizePolicy(sizePolicy)
        self.crop.setObjectName("crop")
        self.horizontalLayout_3.addWidget(self.crop)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_14.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_14)
        self.widget = QtWidgets.QVBoxLayout()
        self.widget.setObjectName("widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_18.setContentsMargins(6, 2, 6, 5)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.px = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.px.sizePolicy().hasHeightForWidth())
        self.px.setSizePolicy(sizePolicy)
        self.px.setMaximum(1.0)
        self.px.setSingleStep(0.05)
        self.px.setProperty("value", 0.5)
        self.px.setObjectName("px")
        self.horizontalLayout_15.addWidget(self.px)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_16.addWidget(self.label_21)
        self.py = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.py.sizePolicy().hasHeightForWidth())
        self.py.setSizePolicy(sizePolicy)
        self.py.setMaximum(1.0)
        self.py.setSingleStep(0.05)
        self.py.setProperty("value", 0.5)
        self.py.setObjectName("py")
        self.horizontalLayout_16.addWidget(self.py)
        self.horizontalLayout_14.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_14)
        self.verticalLayout_12.addWidget(self.groupBox_3)
        self.horizontalGroupBox_4 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        self.horizontalGroupBox_4.setObjectName("horizontalGroupBox_4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.horizontalGroupBox_4)
        self.verticalLayout_13.setContentsMargins(6, 2, 6, 5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_14 = QtWidgets.QLabel(self.horizontalGroupBox_4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_11.addWidget(self.label_14)
        self.rx = QtWidgets.QDoubleSpinBox(self.horizontalGroupBox_4)
        self.rx.setObjectName("rx")
        self.horizontalLayout_11.addWidget(self.rx)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_15 = QtWidgets.QLabel(self.horizontalGroupBox_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.ry = QtWidgets.QDoubleSpinBox(self.horizontalGroupBox_4)
        self.ry.setObjectName("ry")
        self.horizontalLayout_12.addWidget(self.ry)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_16 = QtWidgets.QLabel(self.horizontalGroupBox_4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_13.addWidget(self.label_16)
        self.rz = QtWidgets.QDoubleSpinBox(self.horizontalGroupBox_4)
        self.rz.setObjectName("rz")
        self.horizontalLayout_13.addWidget(self.rz)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_13)
        self.center = QtWidgets.QPushButton(self.horizontalGroupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.center.sizePolicy().hasHeightForWidth())
        self.center.setSizePolicy(sizePolicy)
        self.center.setObjectName("center")
        self.horizontalLayout_7.addWidget(self.center)
        self.verticalLayout_13.addLayout(self.horizontalLayout_7)
        self.verticalLayout_12.addWidget(self.horizontalGroupBox_4)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabWidgetPage1)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setContentsMargins(6, 2, 6, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_20.addWidget(self.label_22)
        self.ox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ox.sizePolicy().hasHeightForWidth())
        self.ox.setSizePolicy(sizePolicy)
        self.ox.setMaximum(1.0)
        self.ox.setSingleStep(0.05)
        self.ox.setProperty("value", 0.5)
        self.ox.setObjectName("ox")
        self.horizontalLayout_20.addWidget(self.ox)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_21.addWidget(self.label_23)
        self.oy = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oy.sizePolicy().hasHeightForWidth())
        self.oy.setSizePolicy(sizePolicy)
        self.oy.setMaximum(1.0)
        self.oy.setSingleStep(0.05)
        self.oy.setProperty("value", 0.5)
        self.oy.setObjectName("oy")
        self.horizontalLayout_21.addWidget(self.oy)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.intensity = QtWidgets.QSlider(self.groupBox_4)
        self.intensity.setOrientation(QtCore.Qt.Horizontal)
        self.intensity.setObjectName("intensity")
        self.horizontalLayout_22.addWidget(self.intensity)
        self.intensityVal = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.intensityVal.setObjectName("intensityVal")
        self.horizontalLayout_22.addWidget(self.intensityVal)
        self.formLayout_5.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_22)
        self.verticalLayout_3.addLayout(self.formLayout_5)
        self.verticalLayout_12.addWidget(self.groupBox_4)
        self.formGroupBox = QtWidgets.QGroupBox(self.tabWidgetPage1)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(6, 2, 6, 5)
        self.formLayout.setObjectName("formLayout")
        self.label_12 = QtWidgets.QLabel(self.formGroupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.formGroupBox)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.blendmode = QtWidgets.QComboBox(self.formGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blendmode.sizePolicy().hasHeightForWidth())
        self.blendmode.setSizePolicy(sizePolicy)
        self.blendmode.setObjectName("blendmode")
        self.blendmode.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.blendmode)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.opacity = QtWidgets.QSlider(self.formGroupBox)
        self.opacity.setMaximum(100)
        self.opacity.setProperty("value", 100)
        self.opacity.setOrientation(QtCore.Qt.Horizontal)
        self.opacity.setInvertedAppearance(False)
        self.opacity.setInvertedControls(False)
        self.opacity.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.opacity.setObjectName("opacity")
        self.horizontalLayout_5.addWidget(self.opacity)
        self.opacityVal = QtWidgets.QDoubleSpinBox(self.formGroupBox)
        self.opacityVal.setMaximum(1.0)
        self.opacityVal.setSingleStep(0.05)
        self.opacityVal.setProperty("value", 1.0)
        self.opacityVal.setObjectName("opacityVal")
        self.horizontalLayout_5.addWidget(self.opacityVal)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.verticalLayout_12.addWidget(self.formGroupBox)
        self.widget.addLayout(self.verticalLayout_12)
        self.horizontalLayout.addLayout(self.widget)
        self.spriteView = RuminaGraphicsView(self.tabWidgetPage1)
        self.spriteView.setObjectName("spriteView")
        self.horizontalLayout.addWidget(self.spriteView)
        self.mapView = QtWidgets.QGraphicsView(self.tabWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapView.sizePolicy().hasHeightForWidth())
        self.mapView.setSizePolicy(sizePolicy)
        self.mapView.setBaseSize(QtCore.QSize(128, 128))
        self.mapView.setObjectName("mapView")
        self.horizontalLayout.addWidget(self.mapView)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tabWidgetPage2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.fileView = RuminaGraphicsView(self.tabWidgetPage2)
        self.fileView.setObjectName("fileView")
        self.verticalLayout_8.addWidget(self.fileView)
        self.tabs = RuminaTabBar(self.tabWidgetPage2)
        self.tabs.setObjectName("tabs")
        self.verticalLayout_8.addWidget(self.tabs)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_18 = QtWidgets.QLabel(self.tabWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.tabWidgetPage2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_4.addWidget(self.label_19)
        self.comboBox = QtWidgets.QComboBox(self.tabWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidgetPage3 = QtWidgets.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tabWidgetPage3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.console = QtWidgets.QPlainTextEdit(self.tabWidgetPage3)
        self.console.setStyleSheet("color: white;\n"
"background-color: black;\n"
"font-family: monospace;\n"
"border: none;")
        self.console.setReadOnly(True)
        self.console.setBackgroundVisible(False)
        self.console.setObjectName("console")
        self.verticalLayout_6.addWidget(self.console)
        self.consoleInput = QtWidgets.QLineEdit(self.tabWidgetPage3)
        self.consoleInput.setStyleSheet("color: white;\n"
"background-color: black;\n"
"font-family: monospace;")
        self.consoleInput.setObjectName("consoleInput")
        self.verticalLayout_6.addWidget(self.consoleInput)
        self.tabWidget.addTab(self.tabWidgetPage3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 834, 28))
        self.menubar.setObjectName("menubar")
        self.menuPlik = QtWidgets.QMenu(self.menubar)
        self.menuPlik.setObjectName("menuPlik")
        self.menuPodgl_d = QtWidgets.QMenu(self.menubar)
        self.menuPodgl_d.setObjectName("menuPodgl_d")
        MainWindow.setMenuBar(self.menubar)
        self.actionOtw_rz = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("file-open")
        self.actionOtw_rz.setIcon(icon)
        self.actionOtw_rz.setObjectName("actionOtw_rz")
        self.actionZapisz = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("save")
        self.actionZapisz.setIcon(icon)
        self.actionZapisz.setObjectName("actionZapisz")
        self.actionPodgl_d = QtWidgets.QAction(MainWindow)
        self.actionPodgl_d.setObjectName("actionPodgl_d")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionRe_import = QtWidgets.QAction(MainWindow)
        self.actionRe_import.setObjectName("actionRe_import")
        self.actionPreview = QtWidgets.QAction(MainWindow)
        self.actionPreview.setObjectName("actionPreview")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.menuPlik.addAction(self.actionNew)
        self.menuPlik.addAction(self.actionOtw_rz)
        self.menuPlik.addSeparator()
        self.menuPlik.addAction(self.actionZapisz)
        self.menuPlik.addAction(self.actionSave_as)
        self.menuPlik.addSeparator()
        self.menuPlik.addAction(self.actionClose)
        self.menuPodgl_d.addAction(self.actionPodgl_d)
        self.menuPodgl_d.addAction(self.actionRedo)
        self.menuPodgl_d.addSeparator()
        self.menuPodgl_d.addAction(self.actionRe_import)
        self.menuPodgl_d.addAction(self.actionPreview)
        self.menubar.addAction(self.menuPlik.menuAction())
        self.menubar.addAction(self.menuPodgl_d.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.sceneGraphicsView, self.name)
        MainWindow.setTabOrder(self.name, self.horizontalSlider)
        MainWindow.setTabOrder(self.horizontalSlider, self.highlighted)
        MainWindow.setTabOrder(self.highlighted, self.hidden)
        MainWindow.setTabOrder(self.hidden, self.x)
        MainWindow.setTabOrder(self.x, self.y)
        MainWindow.setTabOrder(self.y, self.z)
        MainWindow.setTabOrder(self.z, self.scale)
        MainWindow.setTabOrder(self.scale, self.scaleVal)
        MainWindow.setTabOrder(self.scaleVal, self.sx)
        MainWindow.setTabOrder(self.sx, self.sy)
        MainWindow.setTabOrder(self.sy, self.sw)
        MainWindow.setTabOrder(self.sw, self.sh)
        MainWindow.setTabOrder(self.sh, self.crop)
        MainWindow.setTabOrder(self.crop, self.px)
        MainWindow.setTabOrder(self.px, self.py)
        MainWindow.setTabOrder(self.py, self.rx)
        MainWindow.setTabOrder(self.rx, self.ry)
        MainWindow.setTabOrder(self.ry, self.rz)
        MainWindow.setTabOrder(self.rz, self.center)
        MainWindow.setTabOrder(self.center, self.ox)
        MainWindow.setTabOrder(self.ox, self.oy)
        MainWindow.setTabOrder(self.oy, self.intensity)
        MainWindow.setTabOrder(self.intensity, self.intensityVal)
        MainWindow.setTabOrder(self.intensityVal, self.blendmode)
        MainWindow.setTabOrder(self.blendmode, self.opacity)
        MainWindow.setTabOrder(self.opacity, self.opacityVal)
        MainWindow.setTabOrder(self.opacityVal, self.spriteView)
        MainWindow.setTabOrder(self.spriteView, self.mapView)
        MainWindow.setTabOrder(self.mapView, self.consoleInput)
        MainWindow.setTabOrder(self.consoleInput, self.console)
        MainWindow.setTabOrder(self.console, self.fileView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Rumina Editor"))
        self.groupBox.setTitle(_translate("MainWindow", "P&roperties"))
        self.label_10.setText(_translate("MainWindow", "Name:"))
        self.label_11.setText(_translate("MainWindow", "Plane:"))
        self.highlighted.setText(_translate("MainWindow", "Highlighted"))
        self.hidden.setText(_translate("MainWindow", "Hidden"))
        self.horizontalGroupBox_2.setTitle(_translate("MainWindow", "Position"))
        self.label_6.setText(_translate("MainWindow", "X:"))
        self.label_7.setText(_translate("MainWindow", "Y:"))
        self.label_8.setText(_translate("MainWindow", "Z:"))
        self.label_17.setText(_translate("MainWindow", "Scale:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Source"))
        self.label_4.setText(_translate("MainWindow", "File:"))
        self.file.setText(_translate("MainWindow", "file.png"))
        self.label.setText(_translate("MainWindow", "X:"))
        self.label_2.setText(_translate("MainWindow", "Y:"))
        self.label_5.setText(_translate("MainWindow", "H:"))
        self.label_3.setText(_translate("MainWindow", "W:"))
        self.crop.setText(_translate("MainWindow", "Auto crop"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Pivot"))
        self.label_20.setText(_translate("MainWindow", "X:"))
        self.label_21.setText(_translate("MainWindow", "Y:"))
        self.horizontalGroupBox_4.setTitle(_translate("MainWindow", "Rotation"))
        self.label_14.setText(_translate("MainWindow", "X:"))
        self.label_15.setText(_translate("MainWindow", "Y:"))
        self.label_16.setText(_translate("MainWindow", "Z:"))
        self.center.setText(_translate("MainWindow", "Look at center"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Swinging"))
        self.label_22.setText(_translate("MainWindow", "Origin X:"))
        self.label_23.setText(_translate("MainWindow", "Origin Y:"))
        self.label_9.setText(_translate("MainWindow", "Intensivity:"))
        self.formGroupBox.setTitle(_translate("MainWindow", "Blending"))
        self.label_12.setText(_translate("MainWindow", "Mode:"))
        self.label_13.setText(_translate("MainWindow", "Opacity:"))
        self.blendmode.setItemText(0, _translate("MainWindow", "default"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "Edit item"))
        self.label_18.setText(_translate("MainWindow", "SPACE adds selected item."))
        self.label_19.setText(_translate("MainWindow", "Alignment:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "bottom left"))
        self.comboBox.setItemText(1, _translate("MainWindow", "bottom center"))
        self.comboBox.setItemText(2, _translate("MainWindow", "bottom right"))
        self.comboBox.setItemText(3, _translate("MainWindow", "center left"))
        self.comboBox.setItemText(4, _translate("MainWindow", "center center"))
        self.comboBox.setItemText(5, _translate("MainWindow", "center right"))
        self.comboBox.setItemText(6, _translate("MainWindow", "top left"))
        self.comboBox.setItemText(7, _translate("MainWindow", "top center"))
        self.comboBox.setItemText(8, _translate("MainWindow", "top right"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "Add items"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("MainWindow", "Console"))
        self.pushButton.setText(_translate("MainWindow", "Export && launch"))
        self.menuPlik.setTitle(_translate("MainWindow", "&File"))
        self.menuPodgl_d.setTitle(_translate("MainWindow", "Ed&it"))
        self.actionOtw_rz.setText(_translate("MainWindow", "&Open"))
        self.actionZapisz.setText(_translate("MainWindow", "&Save"))
        self.actionPodgl_d.setText(_translate("MainWindow", "&Undo"))
        self.actionRedo.setText(_translate("MainWindow", "&Redo"))
        self.actionRe_import.setText(_translate("MainWindow", "Re-&import"))
        self.actionPreview.setText(_translate("MainWindow", "&Preview"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionNew.setText(_translate("MainWindow", "New"))

from RuminaGraphicsView import RuminaGraphicsView
from RuminaTabBar import RuminaTabBar
